<%@ page pageEncoding="UTF-8" contentType="text/cache-manifest" %>CACHE MANIFEST
# 2012-03-15:v11

# Explicitly cached 'master entries'.
CACHE:
/app/
/static/images/checkbox.gif
/static/images/delete.jpg
/static/js/libs/dojo172/dojo/dojo.js
/static/js/libs/modernizr-2.0.6.min.js
/static/css/style.css
/static/css/site.css
/static/js/libs/todo/widgets/TaskListWidget/css/TaskRow.css
/static/js/libs/dojo172/dojo/main.js
/static/js/libs/dojo172/dojo/_base/kernel.js
/static/js/libs/dojo172/dojo/_base/config.js
/static/js/libs/dojo172/dojo/_base/sniff.js
/static/js/libs/dojo172/dojo/_base/lang.js
/static/js/libs/dojo172/dojo/_base/array.js
/static/js/libs/dojo172/dojo/ready.js
/static/js/libs/dojo172/dojo/domReady.js
/static/js/libs/dojo172/dojo/_base/declare.js
/static/js/libs/dojo172/dojo/_base/connect.js
/static/js/libs/dojo172/dojo/on.js
/static/js/libs/dojo172/dojo/topic.js
/static/js/libs/dojo172/dojo/Evented.js
/static/js/libs/dojo172/dojo/aspect.js
/static/js/libs/dojo172/dojo/_base/event.js
/static/js/libs/dojo172/dojo/dom-geometry.js
/static/js/libs/dojo172/dojo/_base/window.js
/static/js/libs/dojo172/dojo/dom.js
/static/js/libs/dojo172/dojo/dom-style.js
/static/js/libs/dojo172/dojo/mouse.js
/static/js/libs/dojo172/dojo/keys.js
/static/js/libs/dojo172/dojo/_base/Deferred.js
/static/js/libs/dojo172/dojo/_base/json.js
/static/js/libs/dojo172/dojo/json.js
/static/js/libs/dojo172/dojo/_base/Color.js
/static/js/libs/dojo172/dojo/_base/browser.js
/static/js/libs/dojo172/dojo/_base/unload.js
/static/js/libs/dojo172/dojo/_base/html.js
/static/js/libs/dojo172/dojo/dom-attr.js
/static/js/libs/dojo172/dojo/dom-prop.js
/static/js/libs/dojo172/dojo/dom-construct.js
/static/js/libs/dojo172/dojo/dom-class.js
/static/js/libs/dojo172/dojo/_base/NodeList.js
/static/js/libs/dojo172/dojo/query.js
/static/js/libs/dojo172/dojo/selector/_loader.js
/static/js/libs/dojo172/dojo/selector/acme.js
/static/js/libs/dojo172/dojo/NodeList-dom.js
/static/js/libs/dojo172/dojo/_base/xhr.js
/static/js/libs/dojo172/dojo/io-query.js
/static/js/libs/dojo172/dojo/dom-form.js
/static/js/libs/dojo172/dojo/_base/fx.js
/static/js/libs/dojo172/dojo/_base/loader.js
/static/js/libs/dojo172/dojo/_firebug/firebug.js
/static/js/libs/dojo172/dojo/parser.js
/static/js/libs/dojo172/dojo/_base/url.js
/static/js/libs/dojo172/dojo/date/stamp.js
/static/js/libs/dojo172/dojox/rpc/Rest.js
/static/js/libs/dojo172/dojox/main.js
/static/js/libs/todo/widgets/TaskListWidget/TaskListWidget.js
/static/js/libs/dojo172/dojo/text.js
/static/js/libs/dojo172/dijit/_WidgetBase.js
/static/js/libs/dojo172/dojo/Stateful.js
/static/js/libs/dojo172/dijit/registry.js
/static/js/libs/dojo172/dijit/main.js
/static/js/libs/dojo172/dijit/_TemplatedMixin.js
/static/js/libs/dojo172/dojo/touch.js
/static/js/libs/dojo172/dojo/string.js
/static/js/libs/dojo172/dojo/cache.js
/static/js/libs/todo/widgets/TaskListWidget/templates/TaskListWidget.html
/static/js/libs/todo/widgets/TaskListWidget/TaskRowWidget.js
/static/js/libs/todo/widgets/TaskListWidget/templates/TaskRowWidget.html
/static/js/libs/dojo172/dojox/rpc/OfflineRest.js
/static/js/libs/dojo172/dojox/data/ClientFilter.js
/static/js/libs/dojo172/dojo/data/util/filter.js
/static/js/libs/dojo172/dojox/storage.js
/static/js/libs/dojo172/dojox/storage/_common.js
/static/js/libs/dojo172/dojox/storage/Provider.js
/static/js/libs/dojo172/dojox/storage/manager.js
/static/js/libs/dojo172/dojox/storage/LocalStorageProvider.js
/static/js/libs/dojo172/dojox/storage/GearsStorageProvider.js
/static/js/libs/dojo172/dojo/gears.js
/static/js/libs/dojo172/dojox/sql.js
/static/js/libs/dojo172/dojox/sql/_base.js
/static/js/libs/dojo172/dojox/sql/_crypto.js
/static/js/libs/dojo172/dojox/storage/WhatWGStorageProvider.js
/static/js/libs/dojo172/dojox/storage/FlashStorageProvider.js
/static/js/libs/dojo172/dojox/flash.js
/static/js/libs/dojo172/dojox/flash/_base.js
/static/js/libs/dojo172/dojo/window.js
/static/js/libs/dojo172/dojox/storage/BehaviorStorageProvider.js
/static/js/libs/dojo172/dojox/storage/CookieStorageProvider.js
/static/js/libs/dojo172/dojo/cookie.js
/static/js/libs/dojo172/dojo/regexp.js
/static/js/libs/dojo172/dojox/data/JsonRestStore.js
/static/js/libs/dojo172/dojox/rpc/JsonRest.js
/static/js/libs/dojo172/dojox/json/ref.js
/static/js/libs/dojo172/dojox/json/schema.js
/static/js/libs/dojo172/dojox/data/ServiceStore.js
/static/json/schema/todo.webapp.dto.TaskDTO
/static/js/libs/dojo172/dijit/_base/manager.js
/static/js/libs/jquery-1.7.1.min.js
/static/js/libs/dojo172/dojo/has.js

NETWORK:
*